---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pingpongk
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./release
  prune: true
  sourceRef:
    kind: GitRepository
    name: pingpong
  targetNamespace: pthattio

